name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello, world"
      - uses: actions/checkout@v4

name: Workflow
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: date